# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detectionWindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_detectionWindow(object):
    def setupUi(self, detectionWindow):
        detectionWindow.setObjectName("detectionWindow")
        detectionWindow.resize(716, 562)
        self.horizontalLayout = QtWidgets.QHBoxLayout(detectionWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_for_image = QtWidgets.QWidget(detectionWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_for_image.sizePolicy().hasHeightForWidth())
        self.widget_for_image.setSizePolicy(sizePolicy)
        self.widget_for_image.setObjectName("widget_for_image")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget_for_image)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(140, 80, 160, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_for_image = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_for_image.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_for_image.setObjectName("gridLayout_for_image")
        self.verticalLayout.addWidget(self.widget_for_image)
        self.widget_for_samples = QtWidgets.QWidget(detectionWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_for_samples.sizePolicy().hasHeightForWidth())
        self.widget_for_samples.setSizePolicy(sizePolicy)
        self.widget_for_samples.setObjectName("widget_for_samples")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget_for_samples)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(150, 90, 160, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_for_samples = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_for_samples.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_for_samples.setObjectName("gridLayout_for_samples")
        self.verticalLayout.addWidget(self.widget_for_samples)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_experiment_process = QtWidgets.QLabel(detectionWindow)
        self.label_experiment_process.setObjectName("label_experiment_process")
        self.verticalLayout_2.addWidget(self.label_experiment_process)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_get_sample = QtWidgets.QLabel(detectionWindow)
        self.label_get_sample.setObjectName("label_get_sample")
        self.verticalLayout_2.addWidget(self.label_get_sample, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_exposure = QtWidgets.QLabel(detectionWindow)
        self.label_exposure.setObjectName("label_exposure")
        self.verticalLayout_2.addWidget(self.label_exposure, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_collect_data = QtWidgets.QLabel(detectionWindow)
        self.label_collect_data.setObjectName("label_collect_data")
        self.verticalLayout_2.addWidget(self.label_collect_data, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_dump_of_waste_liquid = QtWidgets.QLabel(detectionWindow)
        self.label_dump_of_waste_liquid.setObjectName("label_dump_of_waste_liquid")
        self.verticalLayout_2.addWidget(self.label_dump_of_waste_liquid, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_set_light_resource_title = QtWidgets.QLabel(detectionWindow)
        self.label_set_light_resource_title.setObjectName("label_set_light_resource_title")
        self.verticalLayout_3.addWidget(self.label_set_light_resource_title)
        self.comboBox_set_light_resource = QtWidgets.QComboBox(detectionWindow)
        self.comboBox_set_light_resource.setObjectName("comboBox_set_light_resource")
        self.verticalLayout_3.addWidget(self.comboBox_set_light_resource)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_start_experiment = QtWidgets.QPushButton(detectionWindow)
        self.btn_start_experiment.setObjectName("btn_start_experiment")
        self.verticalLayout_4.addWidget(self.btn_start_experiment)
        self.btn_go_to_analyzeWindow = QtWidgets.QPushButton(detectionWindow)
        self.btn_go_to_analyzeWindow.setObjectName("btn_go_to_analyzeWindow")
        self.verticalLayout_4.addWidget(self.btn_go_to_analyzeWindow)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_comeback_homeWindow = QtWidgets.QPushButton(detectionWindow)
        self.btn_comeback_homeWindow.setObjectName("btn_comeback_homeWindow")
        self.verticalLayout_5.addWidget(self.btn_comeback_homeWindow)
        self.btn_comeback_settingWindow = QtWidgets.QPushButton(detectionWindow)
        self.btn_comeback_settingWindow.setObjectName("btn_comeback_settingWindow")
        self.verticalLayout_5.addWidget(self.btn_comeback_settingWindow)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.horizontalLayout.setStretch(0, 20)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 3)

        self.retranslateUi(detectionWindow)
        QtCore.QMetaObject.connectSlotsByName(detectionWindow)

    def retranslateUi(self, detectionWindow):
        _translate = QtCore.QCoreApplication.translate
        detectionWindow.setWindowTitle(_translate("detectionWindow", "Form"))
        self.label_experiment_process.setText(_translate("detectionWindow", "实验实时监控流程："))
        self.label_get_sample.setText(_translate("detectionWindow", "1.取样"))
        self.label_exposure.setText(_translate("detectionWindow", "2.曝光检测"))
        self.label_collect_data.setText(_translate("detectionWindow", "3.数据收集"))
        self.label_dump_of_waste_liquid.setText(_translate("detectionWindow", "4.倾倒废液"))
        self.label_set_light_resource_title.setText(_translate("detectionWindow", "请配置光源："))
        self.btn_start_experiment.setText(_translate("detectionWindow", "开始实验"))
        self.btn_go_to_analyzeWindow.setText(_translate("detectionWindow", "数据分析"))
        self.btn_comeback_homeWindow.setText(_translate("detectionWindow", "返回主界面"))
        self.btn_comeback_settingWindow.setText(_translate("detectionWindow", "返回设置界面"))

